---
title: "Retail stats in Japan."
date: "2019-09-15"
output: github_document
---

##小売業販売額分析レポート

情報源：https://www.meti.go.jp/statistics/tyo/syoudou/result-2/index.html

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(lubridate)
library(tsibble)
library(feasts)
```

```{r include=FALSE}
# 商業動態統計 販売額 単位10億円
source("Rscript/JPretail.R")
JPretail
```

##データの確認

```{r}
tibble(
  oldest = pull(JPretail, 年月) %>% head(1),
  lastest = pull(JPretail, 年月) %>% tail(1),
  row = JPretail %>% nrow(),
  ncol = JPretail %>% ncol()
 ) 
```




```{r}
JPretail <- 
  JPretail %>% 
  filter(大分類 == "小売業" & 小分類 == "小売業計") %>% 
  select(年月, 販売額)
```




```{r paged.print=FALSE}
JPretail <-
  JPretail %>% 
  mutate(yearmon = yearmonth(年月))  %>% 
  as_tsibble(index = yearmon)
```


## 小売業販売額の推移


```{r}
JPretail %>% 
  autoplot(販売額) +
  theme_grey(base_family="YuGo-Medium",base_size = 13) 
```



```{r}
JPretail %>% 
  filter(year(年月) >= 2010) %>%
  autoplot(販売額) +
  theme_grey(base_family="YuGo-Medium",base_size = 13) 
```



```{r}
JPretail %>% 
  gg_season(販売額) +
  theme_grey(base_family="YuGo-Medium",base_size = 13) 
```


## STL decomposition

```{r}
JPretail %>% 
  rename(value = 販売額) %>% 
  STL(value) %>% 
  autoplot()
```
































